# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  push:
    tags:
      - "release-*" # Trigger the workflow on push events to release-* tags

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          echo "# Changelog for version ${{ github.ref_name }}" > CHANGELOG.md
          gh release view "${{ github.ref_name }}" --json body --jq '.body' >> CHANGELOG.md
