# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  push:
    tags:
      - "release-*" # Trigger the workflow on push events to release-* tags

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Create release on kubernetes-mixin
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          repository: sleepyfoodie/kubernetes-mixin-copy
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
